import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:screenshot/screenshot.dart';
import 'package:gal/gal.dart';
import 'package:share_plus/share_plus.dart';

void main() async { WidgetsFlutterBinding.ensureInitialized(); runApp(const FoodCrushApp()); }

class Product {
  String id, name, category; double price; bool active;
  Product({required this.id, required this.name, required this.category, required this.price, this.active=true});
  Map<String,dynamic> toJson()=>{'id':id,'name':name,'category':category,'price':price,'active':active};
  factory Product.fromJson(Map<String,dynamic> j)=>Product(id:j['id'],name:j['name'],category:j['category']??'Other',price:(j['price'] as num).toDouble(),active:j['active']??true);
}
class Line { Product p; int qty; Line(this.p,this.qty); double get total=>p.price*qty; }
class Bill { String id,date,payment; List<Map<String,dynamic>> items; double total;
  Bill({required this.id,required this.date,required this.payment,required this.items,required this.total});
  Map<String,dynamic> toJson()=>{'id':id,'date':date,'payment':payment,'items':items,'total':total};
  factory Bill.fromJson(Map<String,dynamic> j)=>Bill(id:j['id'],date:j['date'],payment:j['payment'],items:List<Map<String,dynamic>>.from((j['items'] as List).map((e)=>Map<String,dynamic>.from(e))),total:(j['total'] as num).toDouble());
}

class Store extends ChangeNotifier {
  List<Product> products=[]; List<Bill> bills=[];
  Future<void> load() async { final p=await SharedPreferences.getInstance();
    final a=p.getString('products'), b=p.getString('bills');
    products=a==null?_defaults():List<Product>.from((jsonDecode(a) as List).map((e)=>Product.fromJson(e)));
    bills=b==null?[]:List<Bill>.from((jsonDecode(b) as List).map((e)=>Bill.fromJson(e))); notifyListeners(); }
  List<Product> _defaults()=>[
    Product(id:'1',name:'Veg Sandwich',category:'Fast Food',price:70),Product(id:'2',name:'Cheese Sandwich',category:'Fast Food',price:90),
    Product(id:'3',name:'Vada Pav',category:'Fast Food',price:35),Product(id:'4',name:'Dabeli',category:'Fast Food',price:40),
    Product(id:'5',name:'Masala Dosa',category:'Dosa',price:80),Product(id:'6',name:'Cheese Dosa',category:'Dosa',price:110),
    Product(id:'7',name:'Veg Noodles',category:'Chinese',price:100),Product(id:'8',name:'Manchurian',category:'Chinese',price:110),
    Product(id:'9',name:'Pav Bhaji',category:'Fast Food',price:90),Product(id:'10',name:'French Fries',category:'Sides',price:80),
    Product(id:'11',name:'Cold Drink',category:'Beverage',price:40),Product(id:'12',name:'Tea',category:'Beverage',price:20),
  ];
  Future<void> saveProducts() async {final p=await SharedPreferences.getInstance();await p.setString('products',jsonEncode(products.map((e)=>e.toJson()).toList()));notifyListeners();}
  Future<void> saveBills() async {final p=await SharedPreferences.getInstance();await p.setString('bills',jsonEncode(bills.map((e)=>e.toJson()).toList()));notifyListeners();}
}
final store=Store();

class FoodCrushApp extends StatefulWidget {const FoodCrushApp({super.key});@override State<FoodCrushApp> createState()=>_AppState();}
class _AppState extends State<FoodCrushApp>{@override void initState(){super.initState();store.load();}@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'The Food Crush Billing',theme:ThemeData(useMaterial3:true,colorSchemeSeed:const Color(0xFFFFC107),scaffoldBackgroundColor:const Color(0xFFFFFBF0)),home:const Home());}

class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{int tab=0; final cart=<String,Line>{}; String cat='All',search='';
 double get total=>cart.values.fold(0,(s,x)=>s+x.total);int get count=>cart.values.fold(0,(s,x)=>s+x.qty);
 List<String> get cats=>['All',...{...store.products.map((e)=>e.category)}];
 void add(Product p)=>setState(()=>cart[p.id]=cart[p.id]==null?Line(p,1):Line(p,cart[p.id]!.qty+1));
 void sub(Product p)=>setState((){if(!cart.containsKey(p.id))return;if(cart[p.id]!.qty==1)cart.remove(p.id);else cart[p.id]=Line(p,cart[p.id]!.qty-1);});
 @override Widget build(BuildContext c){if(store.products.isEmpty)return const Scaffold(body:Center(child:CircularProgressIndicator()));return Scaffold(appBar:AppBar(backgroundColor:const Color(0xFFFFC107),title:const Text('THE FOOD CRUSH',style:TextStyle(fontWeight:FontWeight.w900)),actions:[IconButton(onPressed:cart.isEmpty?null:showCart,icon:Badge(isLabelVisible:count>0,label:Text('$count'),child:const Icon(Icons.shopping_cart)))]),body:[billing(),Bills(),Products()][tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.point_of_sale),label:'Billing'),NavigationDestination(icon:Icon(Icons.receipt_long),label:'Bills'),NavigationDestination(icon:Icon(Icons.restaurant_menu),label:'Items')]),floatingActionButton:tab==0&&cart.isNotEmpty?FloatingActionButton.extended(onPressed:showCart,icon:const Icon(Icons.receipt),label:Text('₹${total.toStringAsFixed(0)}')):null);}
 Widget billing(){final list=store.products.where((p)=>p.active&&(cat=='All'||p.category==cat)&&p.name.toLowerCase().contains(search.toLowerCase())).toList();return Column(children:[Padding(padding:const EdgeInsets.all(12),child:TextField(onChanged:(v)=>setState(()=>search=v),decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:'Search item...',filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide.none)))),SizedBox(height:44,child:ListView(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:12),children:cats.map((x)=>Padding(padding:const EdgeInsets.only(right:7),child:ChoiceChip(label:Text(x),selected:cat==x,onSelected:(_)=>setState(()=>cat=x)))).toList())),Expanded(child:GridView.builder(padding:const EdgeInsets.all(12),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:10,mainAxisSpacing:10,childAspectRatio:1.25),itemCount:list.length,itemBuilder:(c,i){final p=list[i],q=cart[p.id]?.qty??0;return Card(child:InkWell(onTap:()=>add(p),borderRadius:BorderRadius.circular(16),child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(p.name,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:16)),Text(p.category,style:TextStyle(color:Colors.grey)),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('₹${p.price.toStringAsFixed(0)}',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900)),if(q>0)Text('×$q',style:const TextStyle(fontWeight:FontWeight.w900))])])));}))]);}
 void showCart(){showModalBottomSheet(context:context,isScrollControlled:true,showDragHandle:true,builder:(ctx)=>StatefulBuilder(builder:(ctx,setM)=>SizedBox(height:MediaQuery.of(ctx).size.height*.72,child:Column(children:[const SizedBox(height:8),const Text('CURRENT BILL',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),Expanded(child:ListView(children:cart.values.map((x)=>ListTile(title:Text(x.p.name),subtitle:Text('₹${x.p.price.toStringAsFixed(0)} × ${x.qty}'),trailing:Row(mainAxisSize:MainAxisSize.min,children:[IconButton(onPressed:(){sub(x.p);setM((){});},icon:const Icon(Icons.remove_circle_outline)),Text('${x.qty}'),IconButton(onPressed:(){add(x.p);setM((){});},icon:const Icon(Icons.add_circle_outline))]))).toList())),Padding(padding:const EdgeInsets.all(16),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('TOTAL',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text('₹${total.toStringAsFixed(2)}',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900))])),Padding(padding:const EdgeInsets.fromLTRB(16,0,16,16),child:SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>checkout(ctx),icon:const Icon(Icons.image),label:const Text('GENERATE BILL IMAGE'))))]))));}
 Future<void> checkout(BuildContext sheet)async{String pay='Cash';await showDialog(context:context,builder:(d)=>StatefulBuilder(builder:(d,setD)=>AlertDialog(title:const Text('Payment'),content:Column(mainAxisSize:MainAxisSize.min,children:['Cash','UPI','Card'].map((x)=>RadioListTile(value:x,groupValue:pay,title:Text(x),onChanged:(v){pay=v!;setD((){});})).toList()),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('CANCEL')),FilledButton(onPressed:()=>Navigator.pop(d),child:const Text('CONTINUE'))]));
 final n=DateTime.now();final b=Bill(id:n.millisecondsSinceEpoch.toString(),date:n.toIso8601String(),payment:pay,items:cart.values.map((x)=>{'name':x.p.name,'qty':x.qty,'price':x.p.price,'total':x.total}).toList(),total:total);store.bills.insert(0,b);await store.saveBills();cart.clear();setState((){});if(sheet.mounted)Navigator.pop(sheet);if(mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>BillPreview(bill:b)));}
}

class BillPreview extends StatefulWidget{final Bill bill;const BillPreview({super.key,required this.bill});@override State<BillPreview> createState()=>_BillPreviewState();}
class _BillPreviewState extends State<BillPreview>{final shot=ScreenshotController();bool saving=false;
 Widget receipt(){final b=widget.bill;final dt=DateTime.parse(b.date).toLocal();return Container(width:420,padding:const EdgeInsets.all(24),color:Colors.white,child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Container(padding:const EdgeInsets.all(16),decoration:const BoxDecoration(color:Color(0xFFFFC107),borderRadius:BorderRadius.all(Radius.circular(18))),child:const Column(children:[Text('THE FOOD CRUSH',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),Text('GOOD FOOD • GOOD MOOD',style:TextStyle(fontWeight:FontWeight.w700))])),const SizedBox(height:18),Text('Bill #${b.id.substring(b.id.length-6)}',style:const TextStyle(fontWeight:FontWeight.bold)),Text('${dt.day.toString().padLeft(2,'0')}/${dt.month.toString().padLeft(2,'0')}/${dt.year}  ${dt.hour.toString().padLeft(2,'0')}:${dt.minute.toString().padLeft(2,'0')}'),const Divider(height:28),const Row(children:[Expanded(child:Text('ITEM',style:TextStyle(fontWeight:FontWeight.w900))),SizedBox(width:50,child:Text('QTY',style:TextStyle(fontWeight:FontWeight.w900))),SizedBox(width:80,child:Text('AMT',textAlign:TextAlign.right,style:TextStyle(fontWeight:FontWeight.w900)))]),const SizedBox(height:8),...b.items.map((x)=>Padding(padding:const EdgeInsets.symmetric(vertical:6),child:Row(children:[Expanded(child:Text(x['name'].toString(),style:const TextStyle(fontSize:15))),SizedBox(width:50,child:Text('${x['qty']}')),SizedBox(width:80,child:Text('₹${(x['total'] as num).toStringAsFixed(0)}',textAlign:TextAlign.right))]))),const Divider(height:28),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('PAYMENT'),Text(b.payment)]),const SizedBox(height:10),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('TOTAL',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),Text('₹${b.total.toStringAsFixed(2)}',style:const TextStyle(fontSize:25,fontWeight:FontWeight.w900))]),const SizedBox(height:22),const Text('Thank you for ordering! ❤️',textAlign:TextAlign.center,style:TextStyle(fontWeight:FontWeight.w700)),const SizedBox(height:8),const Text('THE FOOD CRUSH • RATLAM',textAlign:TextAlign.center,style:TextStyle(color:Colors.black54,fontSize:12))]));}
 Future<Uint8List> capture()async=>await shot.captureFromWidget(receipt(),pixelRatio:3.0);
 Future<void> saveGallery()async{setState(()=>saving=true);try{final bytes=await capture();if(!await Gal.hasAccess()){await Gal.requestAccess();}await Gal.putImageBytes(bytes,name:'The_Food_Crush_Bill_${widget.bill.id}');if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('✅ Bill Gallery me save ho gaya')));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Save failed: $e')));}if(mounted)setState(()=>saving=false);}
 Future<void> share()async{final bytes=await capture();final x=await SharePlus.instance.share(ShareParams(files:[XFile.fromData(bytes,mimeType:'image/png',name:'The_Food_Crush_Bill.png')],text:'The Food Crush Bill'));if(mounted&&x.status==ShareResultStatus.success){} }
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Bill Preview'),backgroundColor:const Color(0xFFFFC107)),body:Column(children:[Expanded(child:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Screenshot(controller:shot,child:receipt()))),Padding(padding:const EdgeInsets.fromLTRB(16,8,16,20),child:Row(children:[Expanded(child:FilledButton.icon(onPressed:saving?null:saveGallery,icon:const Icon(Icons.save_alt),label:Text(saving?'SAVING...':'SAVE TO GALLERY'))),const SizedBox(width:10),IconButton.filled(onPressed:share,icon:const Icon(Icons.share))]))]));}

class Bills extends StatelessWidget{const Bills({super.key});@override Widget build(BuildContext c)=>AnimatedBuilder(animation:store,builder:(c,_){if(store.bills.isEmpty)return const Center(child:Text('No bills yet'));final sales=store.bills.fold<double>(0,(s,b)=>s+b.total);return Column(children:[Card(margin:const EdgeInsets.all(12),child:Padding(padding:const EdgeInsets.all(16),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('TOTAL SALES'),Text('₹${sales.toStringAsFixed(2)}',style:const TextStyle(fontSize:26,fontWeight:FontWeight.w900))]),Text('${store.bills.length} bills')])),Expanded(child:ListView.builder(itemCount:store.bills.length,itemBuilder:(c,i){final b=store.bills[i];return ListTile(leading:CircleAvatar(backgroundColor:const Color(0xFFFFC107),child:Text('${i+1}')),title:Text('Bill #${b.id.substring(b.id.length-6)}',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${b.payment} • ${b.items.length} items'),trailing:Text('₹${b.total.toStringAsFixed(0)}',style:const TextStyle(fontWeight:FontWeight.w900)),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>BillPreview(bill:b))));}))]);});}

class Products extends StatelessWidget{const Products({super.key});@override Widget build(BuildContext c)=>AnimatedBuilder(animation:store,builder:(c,_){return ListView(padding:const EdgeInsets.all(12),children:[FilledButton.icon(onPressed:()=>edit(c),icon:const Icon(Icons.add),label:const Text('ADD NEW ITEM')),const SizedBox(height:8),...store.products.map((p)=>Card(child:ListTile(title:Text(p.name,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${p.category} • ₹${p.price.toStringAsFixed(0)}'),leading:Switch(value:p.active,onChanged:(v)async{p.active=v;await store.saveProducts();}),trailing:IconButton(icon:const Icon(Icons.edit),onPressed:()=>edit(c,p))))]);});}
 static Future<void> edit(BuildContext c,[Product? p])async{final n=TextEditingController(text:p?.name??''),cat=TextEditingController(text:p?.category??'Fast Food'),pr=TextEditingController(text:p?.price.toString()??'');await showDialog(context:c,builder:(d)=>AlertDialog(title:Text(p==null?'Add Item':'Edit Item'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Item name')),TextField(controller:cat,decoration:const InputDecoration(labelText:'Category')),TextField(controller:pr,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Price'))]),actions:[TextButton(onPressed:()=>Navigator.pop(d),child:const Text('CANCEL')),FilledButton(onPressed:()async{final price=double.tryParse(pr.text);if(n.text.trim().isEmpty||price==null)return;if(p==null)store.products.add(Product(id:DateTime.now().millisecondsSinceEpoch.toString(),name:n.text.trim(),category:cat.text.trim(),price:price));else{p.name=n.text.trim();p.category=cat.text.trim();p.price=price;}await store.saveProducts();if(d.mounted)Navigator.pop(d);},child:const Text('SAVE'))]));}
}
